# Generated by Django 4.2.4 on 2023-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='isCS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isCustomer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isSales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
