# Generated by Django 4.2.4 on 2023-09-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_address_user_iscs_user_iscustomer_user_issales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isCS',
            new_name='is_cs',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isCustomer',
            new_name='is_customer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isSales',
            new_name='is_sales',
        ),
    ]
