# Generated by Django 4.2.4 on 2023-09-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_username',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
